name: Provision

on:
  push:
    branches:
      - master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  provision:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_DEVELOPMENT }}
